### ISSUE TITLE
Signup form should comply with GDRP

### ISSUE THREAD

**Issue by zdavis** [castiron/manifold-marketing#130]
See:
https://blog.mailchimp.com/gdpr-forms-and-more-tools/?utm_source=email&utm_medium=email&utm_campaign=gdpr&utm_term=us-users&utm_content=gdpr-tools-from-mailchimp&mc_cid=503a0678e7&mc_eid=a6529859ac

https://kb.mailchimp.com/accounts/management/collect-consent-with-gdpr-forms?_ga=2.116119939.449358595.1526396501-1241226977.1525277055

We need the mail chimp sign-up in the footer to go to the mailchimp consent page before the user is added. Doable?

Zach

**Comment by blnkt** [comment]
![screen shot 2018-05-15 at 9 56 57 am](https://user-images.githubusercontent.com/8166060/40071707-6c5304c4-5826-11e8-9929-aa509962fb5e.png)

So @zdavis
These new opt-in options baked into mail chimp are only available for the non-embedded forms so probs not doable in the way we would hope.  However we may be able to create our own form fields and segment our mail chimp audience ourselves in order to still be GDPR considerate.  Another option would be just presenting the user with a button (instead of a button and an email input) to redirect the splash page style sign up form that does support these new GDPR checkboxes.
